spring:
  application:
    name: fast-jmx-api


server:
  port: 9999


fast:
  jmx:
    username: admin
    password: admin
    secret-key: fast-jmx-api


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: fast-jmx-api #JWT加解密使用的密钥【私钥】
  expiration: 28800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头